language: node_js

node_js:
- node

cache:
  yarn: true
  
script:
  - yarn test

deploy:
  provider: npm
  email: bulentv@gmail.com
  api_key:
    secure: "HlSfNsmmb4Hsz+7D5XwNFlrQE6WF8cD+lAqNo8FO4ign3ZeaAO5AFeQCCS4HcYHJwLknxLIpU5tdKNKYsmwS44cdqoLu5kpcUXhUSzgvQ07hsCVFOpbyY5b4FQerO0jYhMqsi7ha+ZW0ofjO1wsilIbDamtQsIi6dA+ZIJwgGzGftp59Ja9ep3MQK/SJnBcV1sld+Ohn25VN9IiixbpPeIw2KEFBoSQcwuA6/Jcp+A6YoVdp0AxG8m61GhREbmQX7p9b7S/lHN4hJkr4qIufl+/0sn3Y07ZP+bq5BLTnH5WXKWoKQeh+MNhbYJXaC1447a5Ol6wmKyePMS9OtZpfVVLk9y/vIsAvopq2dSTqL6Be62BCxNnVikdh7brC/KTHn2GCXUg7hZQT8Fe0YnNLDi8D0uzjPfzMnnb7xkbP8QhCsECrntBOpnpJjzoAsUCrROdlM5bMximtgKJshXaYb99ZGvYSXSyhOomRxVBCnj9SWgatHkWNL5kq4XnzBoUs3c/YHkWdqnMK1wXUYou4ePDrKutr9rSDOkAMJ6IbIMh3bz/adprEsQEq0SlM+819bpvPNIjzsTt9KvPAmrRB76ZsqlsBRtPezsHh4VQ93XOoNFWEj/rMFik2/4uDvAhiJ2gyGAKcm0Zbbi6qfXNDdBL48t5vrOT/jrvSXNpoAS8="    
  on:
    tags: true
    repo: bulentv/js_zklib
